## 分类问题评价指标
- 准确率(Accuracy)
- 精准率(Precision)   在被识别为正类别的样本中，确实为正类别的比例是多少,你认为的正样本，有多少猜对了（猜的准确性如何）。
- 召回率(Recall)  在所有正类别样本中，被正确识别为正类别的比例是多少,正样本有多少被找出来了（召回了多少）
- F1-score

### 混淆矩阵

In [46]:
import numpy as np
from sklearn import datasets

### 针对有偏矩阵效果更好

In [26]:
digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()
# 针对有偏矩阵效果更好
y[digits.target==9] = 1
y[digits.target!=9] = 0

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 666)

In [28]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)
log_reg.score(X_test,y_test)


0.9755555555555555

In [29]:
y_log_predict = log_reg.predict(X_test)

In [30]:
def TN(y_true, y_predict):
    assert len(y_true) == len(y_predict)
    return np.sum((y_true == 0) & (y_predict == 0))

TN(y_test, y_log_predict)

403

In [31]:
def FP(y_true, y_predict):
    assert len(y_true) == len(y_predict)
    return np.sum((y_true == 0) & (y_predict == 1))

FP(y_test, y_log_predict)

2

In [32]:
def FN(y_true, y_predict):
    assert len(y_true) == len(y_predict)
    return np.sum((y_true == 1) & (y_predict == 0))

FN(y_test, y_log_predict)

9

In [33]:
def TP(y_true, y_predict):
    assert len(y_true) == len(y_predict)
    return np.sum((y_true == 1) & (y_predict == 1))

TP(y_test, y_log_predict)

36

In [34]:
def confusion_matrix(y_true, y_predict):
    return np.array([
        [TN(y_true, y_predict), FP(y_true, y_predict)],
        [FN(y_true, y_predict), TP(y_true, y_predict)]
    ])

confusion_matrix(y_test, y_log_predict)

array([[403,   2],
       [  9,  36]])

In [35]:
def precision_score(y_true, y_predict):
    tp = TP(y_true, y_predict)
    fp = FP(y_true, y_predict)
    try:
        return tp / (tp + fp)
    except:
        return 0.0
    
precision_score(y_test, y_log_predict)

0.9473684210526315

In [36]:
def recall_score(y_true, y_predict):
    tp = TP(y_true, y_predict)
    fn = FN(y_true, y_predict)
    try:
        return tp / (tp + fn)
    except:
        return 0.0
    
recall_score(y_test, y_log_predict)

0.8

## scikit-learn中的混淆矩阵，精准率和召回率

In [37]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_log_predict)

array([[403,   2],
       [  9,  36]])

In [38]:
from sklearn.metrics import precision_score
precision_score(y_test, y_log_predict)

0.9473684210526315

In [39]:
from sklearn.metrics import recall_score

recall_score(y_test, y_log_predict)

0.8

## F1-score,精准率与召回率的的调和平均数，倒数和的均值

In [40]:
def f1_score(precision, recall):
    try:
        return 2 * precision * recall / (precision + recall)
    except:
        return 0.0

In [41]:
precision = 0.1
recall = 0.9
f1_score(precision, recall)

0.18000000000000002

In [42]:
precision = 0.0
recall = 1.0
f1_score(precision, recall)


0.0

### sklearn中的F1-score

In [44]:
y_predict = log_reg.predict(X_test)

In [45]:
from sklearn.metrics import f1_score
# 输入为测试数据与预测数据集
f1_score(y_test, y_predict)

0.8674698795180723

## 精准率与召回率的平衡

In [47]:
decision_scores = log_reg.decision_function(X_test)

In [48]:
np.min(decision_scores)

-85.68612416749173

In [49]:
np.max(decision_scores)

19.889606885682948

In [50]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [51]:
confusion_matrix(y_test, y_predict_2)


array([[404,   1],
       [ 21,  24]])

In [52]:
precision_score(y_test, y_predict_2)

0.96

In [53]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [54]:
y_predict_3 = np.array(decision_scores >= -5, dtype='int')

In [55]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]])

In [56]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [57]:
recall_score(y_test, y_predict_3)

0.8888888888888888